name: aqueduct_pd
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  args: ^1.6.0
  crypto: ^2.1.5
  logging: ^0.11.4
  isolate_executor: ^2.0.2+3
  analyzer: '>=0.39.4 <0.41.0'
  jaguar_jwt: ^2.1.6

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
dependency_overrides:
  aqueduct:
    path:  C:\2\aqueduct\
  aqueduct_test:
    path:  C:\2\aqueduct_test\
